### ISSUE TITLE
Добавить на главную странице сайта информацию со страницы "О нас", а именно нижнюю часть "Как мы работаем"

### ISSUE THREAD

**Issue by bratash5** [Kundin/taxi-alex#11]

**Comment by Kundin** [comment]
@bratash5 После отзывов устроит? Со страницы "О нас" убираем?

**Comment by bratash5** [comment]
Думаю лучше после слайдера с калькулятором. Так как люди при заказе трансфера всегда спрашивают как происходит встреча в аэропорту, а так сразу перед газами.

**Comment by Kundin** [comment]
Хорошо. Вполне логично. А второй вопрос?

**Comment by bratash5** [comment]
По второму вопросу убираем со страницы О нас
