### ISSUE TITLE
Добавить на главную страницу слайдер где будут указаны 1. популярные маршруты с ценной, 2. Акции проводимые такси.

### ISSUE THREAD

**Issue by bratash5** [Kundin/taxi-alex#12]

**Comment by Kundin** [comment]
Нужно это подробно обсудить.

**Comment by bratash5** [comment]
Считаю что смешивать маршруты и акции не нужно. сделать разные слайдеры для маршрутов один для акций другой

**Comment by bratash5** [comment]
Слайдер популярных маршрутов:
1. картинка (возможность изменять из админки)
2. слева название маршрута например (Такси аэропорт - Ялта)
3 внизу слева картинки стоимость трансфера (трансфер от ...)
4. внизу справа картинки кнопка забронировать (которая отправляет переносит заказчика сразу в форму онлайн заказа)
