### ISSUE TITLE
Доработки в маршрутах

### ISSUE THREAD

**Issue by bratash5** [Kundin/taxi-alex#13]
Сделать под фотографией, что то вроде калькулятора который будет просчитывать 
1. расстояние, 
2. примерное время в пути, 
3. стоимость поездки от аэропорта до пункта назначения 
4. кнопка заказать такси (отправляет сразу в форму онлайн заказа).

**Comment by Kundin** [comment]
Да, вполне логично и удобно.
Но для этого в админке нужно изменить форму добавления маршрута.
- добавить поле ввода адреса Откуда
- добавить поле ввода адреса Куда

Причем работать будет только для маршрутов, которые есть в базе. 
Например, `Аэропорт Симферополь - Алушта` будет работать, так как есть такой маршрут.
Но вот для маршрута `Аэропорт Симферополь - Международный детский центр «Артек»` так не пойдет, так как в базе нет цены.

Варианты:
1. На таких маршрутах просто не показывать такой калькулятор
2. Определять стоимость поездки по расстоянию.
- Указывать полные адреса Откуда и Куда
- C помощью API Яндекс.Карт прокладывать маршрут и определять расстояние
- На основе расстояния рассчитывать стоимость (нужно указать стоимость километра для разных типов авто)
3. Вручную при создании маршрута указывать стоимость поездки на каждом типе авто (4 цены), расстояние и примерное время в пути.

Наиболее оптимальный последний вариант.

**Comment by bratash5** [comment]
Кака вариант для маршрутов которых нет в базе просчитывать по тому который в базе уже есть 
например в базе нет Аэропорт Симферополь - Международный детский центр «Артек» мы просчитываем Аэропорт Симферополь - Гурзуф так как Артек находится в Гурзуфе и т.д. 
Как считаете?

**Comment by Kundin** [comment]
Да, вполне рабочий вариант.
При создании маршрута вручную указываем откуда и куда с пунктами, которые есть в базе.
Тогда нужно просчитать для всех вариантов расстояние и примерное время в пути с помощью Яндекс.Карт и тогда будут все нужные данные.

Полностью за все (правки в админке + сам калькулятор) - 1500 руб.

**Comment by bratash5** [comment]
Можно сделать? чтоб когда попадаешь на саму форму онлайн заказа она сразу там отображался 
пример: https://taxi-sipaero.ru/transfer-simferopol-laspi/

**Comment by Kundin** [comment]
Да, это можно.

**Comment by bratash5** [comment]
Ок давайте работать денешку скидываю

**Comment by bratash5** [comment]
оплатил

**Comment by Kundin** [comment]
Готово
