### ISSUE TITLE
Сделать кнопку бесплатного звонка 

### ISSUE THREAD

**Issue by bratash5** [Kundin/taxi-alex#17]

**Comment by Kundin** [comment]
То есть заказать звонок?
На телефоне будет кнопка, при нажатии можно сразу делать вызов.
На ПК нужно заказывать звонок, то есть вам будет приходить письмо на почту с номером, а вы перезванивать.
Также можно сохранять в базу и показывать. (как заказы примерно)

Стоимость без базы и админки - 500, иначе 1500 руб.

**Comment by bratash5** [comment]
немного не то имел ввиду хотел https://redconnect.ru/
То вы предложили тоже нужно

**Comment by Kundin** [comment]
Быть может выбрать что-то одно?
Зачем человеку две функции примерно для одного и того же.

**Comment by bratash5** [comment]
Ок давайте поставим  
вот код для сайта
 
<script id="rhlpscrtg" type="text/javascript" charset="utf-8" async="async"
src="https://web.redhelper.ru/service/main.js?c=bratash5"></script>
<div style="display: none"><a class="rc-copyright" 
href="http://redconnect.ru">Обратный звонок RedConnect</a></div>

**Comment by bratash5** [comment]
Код необходимо разместить внутри тега body или head, процедура аналогична установке счётчика посещаемости, например Google Analytics или Яндекс.Метрика.
Подробные инструкции по установке можно прочитать здесь.
