### ISSUE TITLE
Добавить номера телефонов на главной странице вверху 

### ISSUE THREAD

**Issue by bratash5** [Kundin/taxi-alex#18]
верху калькулятора сделать мини слайдер с номерами телефонов и краткой информацией о такси 
пример taxi-sipaero.ru

**Comment by Kundin** [comment]
Не понимаю о чем речь.
В примере вверху калькулятора нет телефонов и краткой информации

**Comment by bratash5** [comment]
У такси сипаэро телефоны снизу ввиде желтой полоски, вот примерно как у них только сразу под меню

**Comment by Kundin** [comment]
Это будет странно выглядеть.
+ вы хотели сделать там слайдер.
Как идея - сделать в слайдере слайд с номерами телефонов и кнопкой "Вызвать такси"

**Comment by bratash5** [comment]
Юра нужно где то разместить номера телефонов вверху сайта. 
Как вариант может сделать меню чуть шире и там номера.
Может у Вас есть какие то мысли на счет этого
