### ISSUE TITLE
SEO-оптимизация

### ISSUE THREAD

**Issue by Kundin** [Kundin/taxi-alex#20]
- [x] Добавить [быстрые ссылки](https://yandex.ru/support/webmaster/search-results/quick-links.xml?#marking)
- [x] Изменить адреса статей на [ЧПУ](http://fb.ru/article/319498/kak-sdelat-chpu-ssyilki-poshagovaya-instruktsiya)
- [x] Добавить разметку в формате [Schema.org](https://yandex.ru/support/webmaster/schema-org/intro-schema-org.html)
- [x] Установить SSL-сертификат
- [x] Сделать 404 страницу. Должна быть ссылка на главную

Адреса статей:
сейчас - `http://taxi-alex24.ru/news/5a588cd20bd11961cb3f6468/`
будет - `http://taxi-alex24.ru/news/ipoteka_v_rossii/`
Второй вариант более понятен и запоминается, а также с такими ссылками можно повысить позицию в поисковиках по запросам.
Если будем менять, то кол-во страниц в поиске "мигнет", то есть в течении недели страницы со старыми адресами будут удалены, а с новыми добавлены.
Ссылка будет автоматически генерироваться по названию статьи - новостей и маршрутов.

Стоимость 1500 руб. (добавил еще пункт)

**Comment by bratash5** [comment]
ок делаем, давно хотел об это написать

**Comment by bratash5** [comment]
Я так понимаю это маршрутов тоже касается)))

**Comment by Kundin** [comment]
Да, маршруты и новости. Хорошо, займусь.
