### ISSUE TITLE
Разработать "заглушку" для мобильной версии

### ISSUE THREAD

**Issue by Kundin** [Kundin/taxi-alex#9]
Так как сейчас еще нет моб.версии, то нужно сделать заглушку.

- [x] Красивый видеофон
- [x] Логотип и название сайта
- [x] Короткое описание сайта
- [x] Кнопка "Заказать такси", которая сразу ведет на вызов номера в телефоне

Стоимость 1000 руб.

**Comment by bratash5** [comment]
Подтверждал адрес

**Comment by Kundin** [comment]
@bratash5 ок

**Comment by bratash5** [comment]
Делаем заглушку для мобильной версии
